[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Cybercrime: Investigating the Role of Intelligent Technologies in Preventing and Combating Cyber Attacks"
